dscauhoi = [
"Người phát minh ra môn bóng rổ là ai?",
"Đầu rồng bằng đất nung có từ thời nào?",
"Sao chổi Ha-Lây là người bạn cũ của nhân loại vào thời ... chinh phạt các nước.",
"Ai là tác gia quan trọng hàng đầu của văn học thời Lê sơ?",
"Thời nào có nhiều khoa thi,tiến sĩ,trạng nguyên,... nhất?",
"Văn học Việt Nam giai đoạn 1945–1954,vua ... là đại diện tiêu biểu nhất của giai đoạn này",
"Ai là người đầu tiên vào vũ trụ?",
"Quốc gia nào là quốc gia đầu tiên và duy nhất bắn hạ được máy bay B-52 của Mỹ",
"Tiếng Latinh của nước nào?",
"Theo truyền thuyết, thành phố Atlantis được xây dựng bởi ai?",
"Người chế tạo ra bom nguyên tử là ai?",
"Ai được công nhận là một trong những nhà vật lý vĩ đại nhất mọi thời đại?",
"Phim Iron Man của hãng nào?",
"Biểu diễn 6 buổi ở Singapore trong vòng 2 tuần?",
]
dscautraloi = [
"James Naismith",
"Trần",
"Vũ Hán Vương",
"Nguyễn Trãi",
"Lê",
"Lê Thánh Tông",
"Yuri Alekseyevich Gagarin",
"Việt Nam",
"Ý",
"Poseidon",
"Julius Robert Oppenheimer",
"Albert Einstein",
"Mavel",
"Taylor Swift",
]
dstraloi = [
"james naismith",
"tran",
"vu han vuong",
"nguyen trai",
"le",
"le thanh tong",
"yuri alekseyevich gagarin",
"viet nam",
"y",
"poseidon",
"julius robert oppenheimer",
"albert einstein",
"mavel",
"taylor swift",
]